---
- name: Deploy Application on Kubernetes
  hosts: 13.232.210.146  # Replace_with your target host group
  become: yes  # Run as root
  tasks:

    - name: Copy Kubernetes Deployment YAML to Master Node
      copy:
        src: ./Deployment.yml  # Ensure this file is in the same directory as playbook
        dest: /home/admin/Deployment.yml
        mode: '0644'

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /home/admin/deployment.yml
      register: kubectl_output
    - name: create new service
      command: kubectl apply -f /home/admin/Service.yml

    - name: Show Deployment Output
      debug:
        msg: "{{ kubectl_output.stdout }}"
