apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 80  # Container's exposed port
  type: LoadBalancer  # Change to NodePort or ClusterIP as per requirement
